ci: only use a single build matrix

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -41,63 +41,85 @@ jobs:
             --skip-cached \
             --systems='x86_64-linux' \
             --flake='${{ env.flake }}#checks.x86_64-linux'
-
-  get-hosts:
+  get-attrs:
     runs-on: ubuntu-latest
     outputs:
-      hosts: ${{ steps.get-hosts.outputs.hosts }}
-      nix-systems: ${{ steps.get-hosts.outputs.hostPlatforms }}
-      gh-systems: ${{ steps.get-hosts.outputs.ghSystems }}
+      attrs: ${{ steps.get-attrs.outputs.attrs }}
+    env:
+      aarch64-ssh-key: ${{ secrets.AARCH64_BUILDER_KEY }}
     steps:
       - uses: DeterminateSystems/nix-installer-action@v5
         with:
           extra-conf: ${{ env.nix-conf }}
-      - id: get-hosts
+      - id: get-attrs
         run: |
           TMP="$(mktemp -d)"
+          # host packages
           nix eval --json '${{ env.flake }}#hosts' | jq -c '
             to_entries
             | map({name: .key} + .value)
             | map_values(
-                if .hostPlatform  == "x86_64-linux" then . + {ghSystem: "ubuntu-latest"}
-                elif .hostPlatform == "aarch64-linux" then . + {ghSystem: "ubuntu-latest"}
-                elif .hostPlatform == "x86_64-darwin" then . + {ghSystem: "macos-latest"}
-                else . + {ghSystem: null} end)
-            | map(select(.ghSystem != null))
-          ' > "$TMP/hosts.json"
+                if .hostPlatform  == "x86_64-linux" then . + {runsOn: "ubuntu-latest"}
+                elif .hostPlatform == "aarch64-linux" then . + {runsOn: "ubuntu-latest"}
+                elif .hostPlatform == "x86_64-darwin" then . + {runsOn: "macos-latest"}
+                else . + {runsOn: null} end)
+            | map(select(.runsOn != null))
+            | map({
+                name,
+                runsOn,
+                hostPlatform,
+                attr: "${{ env.flake }}#packages.\(.hostPlatform).\(.name)"
+              })
+          ' >"$TMP/hostAttrs.json"
 
+          # check that we can build aarch64-linux hosts
+          if [[ -z "${aarch64-ssh-key}" ]]; then
+            echo "::warning title=Incomplete CI run::Not all attributes will be built since no AArch64 SSH key is available"
+            old_host_attrs="$(<"$TMP/hostAttrs.json")"
+            jq -c '
+                map(select(.hostPlatform != "aarch64-linux"))
+            ' <<<"$old_host_attrs" \
+              >"$TMP/hostAttrs.json"
+          fi
+
+          # dev shells
           jq -c '
-            map({hostPlatform, ghSystem})
-            | unique_by(.hostPlatform)
-            | sort_by(.ghSystem)
-          ' \
-          < "$TMP/hosts.json" \
-          > "$TMP/hostPlatforms.json"
+            unique_by(.hostPlatform)
+            | sort_by(.runsOn)
+            | map(
+                .attr = "${{ env.flake }}#devShells.\(.hostPlatform).default.inputDerivation"
+                | .name = "shell-\(.hostPlatform)"
+              )
+          ' <"$TMP/hostAttrs.json" \
+            >"$TMP/shellAttrs.json"
 
-          jq -c <<EOF >"$TMP/ghSystems.json"
-          {
-            "ubuntu-latest": "x86_64-linux",
-            "macos-latest": "x86_64-darwin"
-          }
-          EOF
+          # join attrs
+          jq -s add "$TMP/hostAttrs.json" "$TMP/shellAttrs.json" > "$TMP/attrs.json"
 
-          {
-            echo "hosts=$(cat "$TMP/hosts.json")"
-            echo "hostPlatforms=$(cat "$TMP/hostPlatforms.json")"
-            echo "ghSystems=$(cat "$TMP/ghSystems.json")"
-          } >> "$GITHUB_OUTPUT"
+          # check for dupes
+          duplicate_count="$(jq -r '
+            group_by([.name, .attr])
+            | map(select(length>1))
+            | length
+          ' < "$TMP/attrs.json")"
+          if [[ "$duplicate_count" -ne 0 ]]; then
+            echo "::error title=Duplicate attrs::Duplicate entries in attrs.json: \`$(cat "$TMP/attrs.json")\`"
+            exit 1
+          fi
 
-  build-shell:
-    name: build-shell (${{ matrix.system.hostPlatform }})
-    runs-on: ${{ matrix.system.ghSystem }}
-    needs: [ get-hosts ]
+          echo "attrs=$(<"$TMP/attrs.json")" >> "$GITHUB_OUTPUT"
+
+  build:
+    name: build ${{ matrix.attrs.name }}
+    runs-on: ${{ matrix.attrs.runsOn }}
+    needs: [ get-attrs ]
     strategy:
       fail-fast: false
       matrix:
-        system: ${{ fromJson(needs.get-hosts.outputs.nix-systems) }}
+        attrs: ${{ fromJson(needs.get-attrs.outputs.attrs) }}
     env:
       aarch64-ssh-key: ${{ secrets.AARCH64_BUILDER_KEY }}
-      system: ${{ matrix.system.hostPlatform }}
+      system: ${{ matrix.attrs.hostPlatform }}
     steps:
       - uses: DeterminateSystems/nix-installer-action@v5
         with:
@@ -114,79 +136,21 @@ jobs:
           echo '${{ env.aarch64-ssh-known-host }}' >> ~/.ssh/known_hosts
           echo '${{ env.aarch64-ssh-key }}' > ~/.ssh/id_ed25519
           chmod 0600 ~/.ssh/*
-      - name: build-shell
-        if: ${{ env.system != 'aarch64-linux' || env.aarch64-ssh-key != '' }}
+      - name: nix-build
         run: |
           declare -a args=(
             '--no-nom'
             '--skip-cached'
             '--systems=${{ env.system }}'
+            '--option' 'accept-flake-config' 'true'
           )
-          if [[ '${{ env.system }}' == 'aarch64-linux' ]]; then
-            args+=(
-              '--remote=${{ env.aarch64-host }}'
-              '--option' 'accept-flake-config' 'true'
-            )
-          fi
-          args+=(
-            '--flake=${{ env.flake }}#devShells.${{ env.system }}.default.inputDerivation'
-          )
+          [[ '${{ env.system }}' == 'aarch64-linux' ]] && args+=('--remote=${{ env.aarch64-host }}')
+          args+=('--flake=${{ matrix.attrs.attr }}')
           nix run '${{ env.flake }}#nix-fast-build' -- "${args[@]}"
-
-  build-host:
-    name: build-${{ matrix.host.name }}
-    runs-on: ${{ matrix.host.ghSystem }}
-    needs: [ get-hosts ]
-    strategy:
-      fail-fast: false
-      matrix:
-        host: ${{ fromJson(needs.get-hosts.outputs.hosts) }}
-    env:
-      aarch64-ssh-key: ${{ secrets.AARCH64_BUILDER_KEY }}
-      system: ${{ matrix.host.hostPlatform }}
-    steps:
-      - uses: DeterminateSystems/nix-installer-action@v5
-        with:
-          extra-conf: ${{ env.nix-conf }}
-      - uses: cachix/cachix-action@v12
-        with:
-          name: nix-config
-          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
-      - name: setup-aarch64-ssh
-        if: ${{ env.system == 'aarch64-linux' }}
-        run: |
-          mkdir -p ~/.ssh
-          echo '${{ env.aarch64-ssh-config }}' > ~/.ssh/config
-          echo '${{ env.aarch64-ssh-known-host }}' >> ~/.ssh/known_hosts
-          echo '${{ env.aarch64-ssh-key }}' > ~/.ssh/id_ed25519
-          chmod 0600 ~/.ssh/*
-      - name: build-host
-        if: ${{ env.system != 'aarch64-linux' || env.aarch64-ssh-key != '' }}
-        uses: nick-fields/retry@v2
-        with:
-          timeout_minutes: 720
-          max_attempts: 3
-          retry_on: error
-          command: |
-            declare -a args=(
-              '--no-nom'
-              '--skip-cached'
-              '--systems=${{ env.system }}'
-            )
-            if [[ '${{ env.system }}' == 'aarch64-linux' ]]; then
-              args+=(
-                '--remote=${{ env.aarch64-host }}'
-                '--option' 'accept-flake-config' 'true'
-              )
-            fi
-            args+=(
-              '--flake=${{ env.flake }}#packages.${{ env.system }}.${{ matrix.host.name }}'
-            )
-            nix run '${{ env.flake }}#nix-fast-build' -- "${args[@]}"
 
   check:
     runs-on: ubuntu-latest
-    needs: [ flake-check, build-host, build-shell ]
+    needs: [ flake-check, build ]
     if: always()
     steps:
       - uses: re-actors/alls-green@release/v1
